version: '3.9'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Django

  web:
    build: .
    command: sh -c "python3 directory/manage.py migrate && gunicorn directory.wsgi:application --bind 0.0.0.0:8000 && sleep 3 && python3 directory/manage.py test"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - dev-db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
