version: '3.9'
services:
  localhost:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: Django

  web:
    build: .
    command: sh -c "python3 manage.py migrate & celery -A directory worker -l info & gunicorn directory.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - localhost

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
