name: Deploy to EC2 after merge

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd directory/
          docker-compose build
          docker image ls
          docker tag directory_web:latest zakilu/directory-web:latest
          docker push zakilu/directory-web:latest

      - name: deploy to ec2
        uses: appleboy/ssh-action@master
        env:
          BRANCH: ${{ github.head_ref }}
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: BRANCH
          script: |
            echo "Hello from github action, start deploy ${BRANCH} to ec2"
            docker compose up -d
