name: Deploy to EC2 after merge

on:
  push:
    branches:
      - test
      - develop

jobs:
  test:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker container for testing
        run: |
          cd directory/
          docker compose up -d --build

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r directory/requirements.txt

      - name: Run tests
        run: |
          cd directory/
          python3 manage.py test
